import {Window} from 'happy-dom';
import {UI, type Panel} from '../src/ui/ui';
import {loadSave, type SaveData} from '../src/app/save';
import {VEHICLES} from '../src/config/vehicles';
const window=new Window({url:'http://localhost/'});
Object.assign(globalThis,{window,document:window.document,localStorage:window.localStorage,matchMedia:()=>({matches:false}),HTMLInputElement:window.HTMLInputElement,HTMLSelectElement:window.HTMLSelectElement});
Object.defineProperty(globalThis,'navigator',{value:window.navigator,configurable:true});
window.document.body.innerHTML='<div id="app"></div>';
let save=loadSave(),drives=0;
let ui:UI;
const update=(change:Partial<SaveData>)=>{save={...save,...change};ui.setSave(save);};
ui=new UI(save,{drive:()=>{drives++;},open:(panel:Panel)=>ui.showPanel(panel),selectVehicle:id=>update({vehicleId:id}),selectPaint:paint=>update({paint}),saveSettings:update,graphicsSetting:(key,value)=>{save.graphicsOverrides={...save.graphicsOverrides,[key]:value};ui.setSave(save,false);},resume:()=>{},reset:()=>{},mainMenu:()=>{},toggleCamera:()=>{},pause:()=>{}});
const click=(selector:string)=>{const el=window.document.querySelector<HTMLElement>(selector);if(!el)throw new Error(`Missing ${selector}`);el.click();};
click('[data-panel="garage"]');
if(window.document.querySelectorAll('[data-paint]').length!==8)throw new Error('Paint roster did not render');
click('[data-action="nextVehicle"]');
if(save.vehicleId!==VEHICLES[1].id)throw new Error('Vehicle selection failed');
click('[data-paint="5"]');if(save.paint!==5)throw new Error('Paint selection failed');
click('[data-action="drive"]');if(drives!==1)throw new Error('Drive action failed');
ui.showPanel('settings');
const shadow=window.document.querySelector<HTMLSelectElement>('[data-graphic="shadows"]')!;shadow.value='0';shadow.dispatchEvent(new window.Event('change'));
if(save.graphicsOverrides.shadows!==0)throw new Error('Graphics override failed');
ui.showHUD();ui.updateHUD({speed:72.4,rpm:4120,gear:'3',health:97,traction:1,water:false},18.5,'Falcon XR','downtown','0 / 0','CHASE');
if(window.document.querySelector('#speed')?.textContent!=='072'||window.document.querySelector('#gear')?.textContent!=='3')throw new Error('HUD telemetry failed');
console.log(JSON.stringify({menus:'pass',vehicles:VEHICLES.length,paints:8,graphics:'pass',hud:'pass'}));
window.happyDOM.cancelAsync();
